### PR TITLE
Poly

### PR DESCRIPTION
**Pull request by PolyAnthi**
Fixed several things such as:
simple -> simple.lower()
Removed JSONResponse from imports (isn't needed)

Added:
/roast endpoint
/trivia endpoint
/fact endpoint

All endpoints were tested and simple change was tested.

### CODE REVIEW

**Review by itsnotrin — APPROVED** [review]
Happy with those changse

**Review by itsnotrin — CHANGES_REQUESTED** [review]
Don't use another API for trivia. Denied.

**Review by Dhravya — APPROVED** [review]
looks good. might wanna add statistics.json in the gitignore so that we can easily push pull etc.

**Comment by Dhravya** [comment]
@itsnotrin i think its fixed now review wen

**Pull request merged**
